networks:
  public:
  service:
  cloudflare:
    ipam:
      config:
        - subnet: 172.20.0.0/16

include:
  - ./services/networking/compose.yml
  - ./services/tracking/compose.yml
  - ./services/storage/compose.yml
  - ./services/dev/compose.yml
