networks:
  public:
  service:

include:
  - services/cloudflared/compose.yml
  - services/postgres/compose.yml
  - services/forgejo/compose.yml
  - services/caddy/compose.yml
  - services/media/compose.yml
  - services/misc/compose.yml
