services:
  umami:
    image: docker.umami.is/umami-software/umami:postgresql-latest
    restart: unless-stopped

    networks:
      - public
      - service

    environment:
      - DATABASE_URL=postgresql://umami:${UMAMI_PASSWORD}@postgres:5432/umami

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`tracking.hearth.land`)"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"

      - "traefik.http.routers.umami-public.rule=Host(`tracking.hearth.is-a.dev`)"
      - "traefik.http.routers.umami-public.entryPoints=cloudflare"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped

    networks:
      - service

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/volumes/prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped

    networks:
      - public
      - service

    volumes:
      - /srv/volumes/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.hearth.land`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

      - "traefik.http.routers.grafana-public.rule=Host(`grafana.hearth.is-a.dev`)"
      - "traefik.http.routers.grafana-public.entryPoints=cloudflare"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped

    network_mode: host
    pid: host

    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
