global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node_exporter
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: traefik
    static_configs:
      - targets: ["traefik:8082"]
