services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      POSTGRES_MULTIPLE_DATABASES: forgejo:${FORGEJO_PASSWORD},umami:${UMAMI_PASSWORD}

    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d
      - /srv/volumes/postgres:/var/lib/postgresql/data

    ports:
      - 5432:5432

    networks:
      - service
