services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      POSTGRES_MULTIPLE_DATABASES: forgejo:${FORGEJO_PASSWORD},umami:${UMAMI_PASSWORD},mastodon:${MASTODON_PASSWORD} # sekrit exposed

    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d
      - /srv/volumes/postgres:/var/lib/postgresql/data

    ports:
      - 5432:5432

    networks:
      - service

  copyparty:
    image: ghcr.io/9001/copyparty-ac:latest
    restart: unless-stopped

    hostname: hearth

    networks:
      - public

    volumes:
      - /data/personal:/w
      - ./copyparty:/cfg

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copyparty.rule=Host(`files.hearth.land`)"
      - "traefik.http.services.copyparty.loadbalancer.server.port=3923"

      - "traefik.http.routers.copyparty-public.rule=Host(`files.hearth.is-a.dev`)"
      - "traefik.http.routers.copyparty-public.entryPoints=cloudflare"
