services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: forgejo,dev

    ports:
      - 5432:5432

    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - /srv/docker/volumes/postgres/data:/var/lib/postgresql/data

    networks:
      - service
