services:
  caddy:
    image: caddy:latest
    restart: unless-stopped

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./config:/etc/caddy
      - /srv/http:/srv/http

      - /srv/docker/volumes/caddy/data:/data
      - /srv/docker/volumes/caddy/config:/config
      - /srv/docker/volumes/caddy/logs:/var/log/caddy

      - ./.certs:/etc/ssl/hoshino:ro
      - ../../data/lander:/srv/lander

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - public
