# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3.json

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    asDefault: true
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    asDefault: true
    http:
      tls:
        certResolver: step
    transport:
      respondingTimeouts:
        readTimeout: "0"
        writeTimeout: "0"

  cloudflare:
    address: ":90"
    forwardedHeaders:
      trustedIPs:
        - 172.20.0.0/16
    http:
      middlewares:
        - cloudflarewarp@file
    transport:
      respondingTimeouts:
        readTimeout: "0"
        writeTimeout: "0"

  metrics:
    address: ":8082"

providers:
  docker:
    exposedByDefault: false

  file:
    directory: /etc/traefik
    filename: dynamic.yml
    watch: true

certificatesResolvers:
  step:
    acme:
      tlsChallenge: {}
      email: admin
      storage: /etc/acme/acme.json
      caServer: https://step-ca/acme/acme/directory
      certificatesDuration: 2160
      httpChallenge:
        entryPoint: web

experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"

metrics:
  prometheus:
    addRoutersLabels: true
    entryPoint: metrics
    headerLabels:
      useragent: User-Agent
